<a href="https://colab.research.google.com/github/adithyamauryakr/pytorchtutorials/blob/main/nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NN modules

Key components:
* modules(Layers):
* Activation Functions:
* Loss Functions
* Container Modules

In [8]:
import torch
import torch.nn as nn


class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3) # single neuron
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.sigmoid(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out


In [9]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features)


tensor([[0.3512],
        [0.3613],
        [0.3568],
        [0.3636],
        [0.3718],
        [0.3568],
        [0.3686],
        [0.3774],
        [0.3562],
        [0.3497]], grad_fn=<SigmoidBackward0>)

In [11]:
model.linear1.weight, model.linear1.bias

(Parameter containing:
 tensor([[-0.2368, -0.3315, -0.2041, -0.3944, -0.4193],
         [ 0.1967,  0.2334, -0.3925,  0.2249, -0.4158],
         [ 0.1985, -0.2769,  0.3395,  0.1384, -0.4197]], requires_grad=True),
 Parameter containing:
 tensor([-0.1581,  0.1459,  0.3071], requires_grad=True))

In [4]:
!pip install torchinfo

In [12]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─Sigmoid: 1-2                           [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [19]:
import torch
import torch.nn as nn


class ImproviseModel(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid())

  def forward(self, features):
    out = self.network(features)
    return out


In [20]:
features = torch.rand(10, 5)

model = ImproviseModel(features.shape[1])

model(features)
# summary(model, input_size=(10, 5))

tensor([[0.4513],
        [0.4597],
        [0.4619],
        [0.4619],
        [0.4467],
        [0.4619],
        [0.4546],
        [0.4616],
        [0.4500],
        [0.4609]], grad_fn=<SigmoidBackward0>)