<a href="https://colab.research.google.com/github/adithyamauryakr/pytorchtutorials/blob/main/tensorsinpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors: data structures specialised multi-dimensional array for mathematical
and computational efficiency

In [1]:
import torch
torch.__version__

'2.5.1+cu124'

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

## Creating a tensor:

In [4]:
a = torch.empty(2, 3)
a, type(a)

(tensor([[3.6022e-12, 7.1223e+28, 3.0958e-18],
         [2.6532e+20, 1.9062e+37, 1.1290e+27]]),
 torch.Tensor)

In [5]:
torch.zeros(2,4) # initial biases sometimes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2, 3)

tensor([[0.3578, 0.7104, 0.3438],
        [0.3481, 0.3595, 0.5848]])

In [8]:
torch.manual_seed(42)

In [9]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [10]:
torch.tensor([[2,34,5],[32,4,34.]])

tensor([[ 2., 34.,  5.],
        [32.,  4., 34.]])

In [14]:
print('arange: \n', torch.arange(0,10,3))
print('linspace: \n', torch.linspace(0,10,10))
print('eye: \n', torch.eye(5))
print('full:\n', torch.full((2,3), 5))

arange: 
 tensor([0, 3, 6, 9])
linspace: 
 tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
eye: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full:
 tensor([[5, 5, 5],
        [5, 5, 5]])


In [15]:
x = torch.tensor([[1,3,5], [4,5,6]])
x

tensor([[1, 3, 5],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
# build a tensor of shape of another tensor
torch.empty_like(x)

tensor([[2318330554153050739, 6877682122580386594, 3978121279908900453],
        [8030888409031647276, 2482735057479098226, 7863883273619185722]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x) # doesn't work because x has all integers and rand generates floats

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [21]:
x.dtype

torch.int64

In [22]:
## assign data type:
torch.tensor([1.,3.,5.], dtype=torch.int32)

tensor([1, 3, 5], dtype=torch.int32)

In [23]:
torch.tensor([1,3,5,32], dtype=torch.float32)

tensor([ 1.,  3.,  5., 32.])

In [24]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [25]:
# mathematical operations:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [26]:
x +2, x - 2, x * 3, x /3,x**2, (x * 100)//3,

(tensor([[2.8694, 2.5677],
         [2.7411, 2.4294]]),
 tensor([[-1.1306, -1.4323],
         [-1.2589, -1.5706]]),
 tensor([[2.6082, 1.7031],
         [2.2233, 1.2882]]),
 tensor([[0.2898, 0.1892],
         [0.2470, 0.1431]]),
 tensor([[0.7559, 0.3223],
         [0.5492, 0.1844]]),
 tensor([[28., 18.],
         [24., 14.]]))

In [27]:
#element wise operations:
a = torch.rand(2,3)
b = torch.rand(2,3)
a +b, a-b, a*b, a/b, a**b, a%b

# mod: a%b

(tensor([[1.1824, 1.4056, 0.3719],
         [0.8969, 0.6284, 0.6407]]),
 tensor([[ 0.5885, -0.2578,  0.1613],
         [ 0.3580, -0.0892,  0.2420]]),
 tensor([[0.2629, 0.4773, 0.0281],
         [0.1691, 0.0967, 0.0880]]),
 tensor([[2.9821, 0.6900, 2.5313],
         [2.3282, 0.7515, 2.2139]]),
 tensor([[0.9645, 0.6301, 0.8700],
         [0.8820, 0.6248, 0.8495]]),
 tensor([[0.2916, 0.5739, 0.0560],
         [0.0885, 0.2696, 0.0426]]))

In [28]:
c = torch.tensor([1,-4,2,-4])
torch.abs(c)

tensor([1, 4, 2, 4])

In [29]:
torch.neg(c)

tensor([-1,  4, -2,  4])

In [30]:
torch.round(a)

tensor([[1., 1., 0.],
        [1., 0., 0.]])

In [31]:
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
torch.floor(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
torch.clamp(c, min=-2, max=2)

tensor([ 1, -2,  2, -2])

In [39]:
## reduction operation:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 4., 9.],
        [6., 2., 0.]])

In [36]:
torch.sum(e)

tensor(32)

In [37]:
torch.sum(e,dim=0)

tensor([ 7, 14, 11])

In [38]:
torch.sum(e,dim=1)

tensor([18, 14])

In [40]:
torch.mean(e)
torch.max(e)
torch.min(e)
torch.median(e)
torch.prod(e)


tensor(0.)

In [41]:
torch.std(e)
torch.var(e)

tensor(10.)

In [42]:
torch.argmax(e)

tensor(2)

In [43]:
torch.argmin(e)

tensor(5)

In [44]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2),low=0, high=5)


In [45]:
# matrix operations:
torch.matmul(f,g)

tensor([[24, 56],
        [48, 62]])

In [48]:
torch.dot(torch.tensor([1,3,4,5]), torch.tensor([1,34,3,2]))

tensor(125)

In [50]:
torch.transpose(f, 0, 1)

tensor([[6, 9],
        [2, 7],
        [7, 3]])

In [52]:
torch.det(torch.rand(3,3))

tensor(-0.2229)

In [53]:
torch.rand((3,3)) > torch.rand((3,3))

tensor([[False, False, False],
        [ True,  True,  True],
        [ True, False, False]])

In [57]:
k = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
k

tensor([[0., 9., 8.],
        [5., 3., 7.]])

In [58]:
torch.log(k), torch.exp(k), torch.sqrt(k), torch.sigmoid(k), torch.softmax(k, dim=0), torch.relu(k)

(tensor([[  -inf, 2.1972, 2.0794],
         [1.6094, 1.0986, 1.9459]]),
 tensor([[1.0000e+00, 8.1031e+03, 2.9810e+03],
         [1.4841e+02, 2.0086e+01, 1.0966e+03]]),
 tensor([[0.0000, 3.0000, 2.8284],
         [2.2361, 1.7321, 2.6458]]),
 tensor([[0.5000, 0.9999, 0.9997],
         [0.9933, 0.9526, 0.9991]]),
 tensor([[0.0067, 0.9975, 0.7311],
         [0.9933, 0.0025, 0.2689]]),
 tensor([[0., 9., 8.],
         [5., 3., 7.]]))

In [59]:
## inplace operations
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])
tensor([[0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340]])


In [60]:
m +n

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [61]:
# store the result on m + n in the memory of m
m.add_(n)

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [62]:
torch.relu(m)

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [63]:
m.relu_()

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])