<a href="https://colab.research.google.com/github/adithyamauryakr/pytorchtutorials/blob/main/tensorsinpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors: data structures specialised multi-dimensional array for mathematical
and computational efficiency

In [2]:
import torch
torch.__version__

'2.5.1+cu124'

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

## Creating a tensor:

In [4]:
a = torch.empty(2, 3)
a, type(a)

(tensor([[2.8026e-45, 1.1210e-44, 2.8026e-45],
         [1.2612e-44, 1.5723e-42, 0.0000e+00]]),
 torch.Tensor)

In [5]:
torch.zeros(2,4) # initial biases sometimes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2, 3)

tensor([[0.2897, 0.3101, 0.1975],
        [0.5507, 0.5213, 0.1909]])

In [8]:
torch.manual_seed(42)

In [9]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [10]:
torch.tensor([[2,34,5],[32,4,34.]])

tensor([[ 2., 34.,  5.],
        [32.,  4., 34.]])

In [11]:
print('arange: \n', torch.arange(0,10,3))
print('linspace: \n', torch.linspace(0,10,10))
print('eye: \n', torch.eye(5))
print('full:\n', torch.full((2,3), 5))

arange: 
 tensor([0, 3, 6, 9])
linspace: 
 tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
eye: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full:
 tensor([[5, 5, 5],
        [5, 5, 5]])


In [12]:
x = torch.tensor([[1,3,5], [4,5,6]])
x

tensor([[1, 3, 5],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
# build a tensor of shape of another tensor
torch.empty_like(x)

tensor([[    133027351424400,           133060384,                   0],
        [                  0,                   0, 7310593858020254331]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x) # doesn't work because x has all integers and rand generates floats

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [18]:
x.dtype

torch.int64

In [19]:
## assign data type:
torch.tensor([1.,3.,5.], dtype=torch.int32)

tensor([1, 3, 5], dtype=torch.int32)

In [20]:
torch.tensor([1,3,5,32], dtype=torch.float32)

tensor([ 1.,  3.,  5., 32.])

In [21]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [22]:
# mathematical operations:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [23]:
x +2, x - 2, x * 3, x /3,x**2, (x * 100)//3,

(tensor([[2.8694, 2.5677],
         [2.7411, 2.4294]]),
 tensor([[-1.1306, -1.4323],
         [-1.2589, -1.5706]]),
 tensor([[2.6082, 1.7031],
         [2.2233, 1.2882]]),
 tensor([[0.2898, 0.1892],
         [0.2470, 0.1431]]),
 tensor([[0.7559, 0.3223],
         [0.5492, 0.1844]]),
 tensor([[28., 18.],
         [24., 14.]]))

In [24]:
#element wise operations:
a = torch.rand(2,3)
b = torch.rand(2,3)
a +b, a-b, a*b, a/b, a**b, a%b

# mod: a%b

(tensor([[1.1824, 1.4056, 0.3719],
         [0.8969, 0.6284, 0.6407]]),
 tensor([[ 0.5885, -0.2578,  0.1613],
         [ 0.3580, -0.0892,  0.2420]]),
 tensor([[0.2629, 0.4773, 0.0281],
         [0.1691, 0.0967, 0.0880]]),
 tensor([[2.9821, 0.6900, 2.5313],
         [2.3282, 0.7515, 2.2139]]),
 tensor([[0.9645, 0.6301, 0.8700],
         [0.8820, 0.6248, 0.8495]]),
 tensor([[0.2916, 0.5739, 0.0560],
         [0.0885, 0.2696, 0.0426]]))

In [25]:
c = torch.tensor([1,-4,2,-4])
torch.abs(c)

tensor([1, 4, 2, 4])

In [26]:
torch.neg(c)

tensor([-1,  4, -2,  4])

In [27]:
torch.round(a)

tensor([[1., 1., 0.],
        [1., 0., 0.]])

In [28]:
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
torch.floor(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [30]:
torch.clamp(c, min=-2, max=2)

tensor([ 1, -2,  2, -2])

In [31]:
## reduction operation:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [0., 5., 9.]])

In [32]:
torch.sum(e)

tensor(32.)

In [33]:
torch.sum(e,dim=0)

tensor([ 7., 14., 11.])

In [34]:
torch.sum(e,dim=1)

tensor([18., 14.])

In [35]:
torch.mean(e)
torch.max(e)
torch.min(e)
torch.median(e)
torch.prod(e)


tensor(0.)

In [36]:
torch.std(e)
torch.var(e)

tensor(13.8667)

In [37]:
torch.argmax(e)

tensor(1)

In [38]:
torch.argmin(e)

tensor(3)

In [39]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2),low=0, high=5)


In [40]:
# matrix operations:
torch.matmul(f,g)

tensor([[29, 49],
        [10, 20]])

In [41]:
torch.dot(torch.tensor([1,3,4,5]), torch.tensor([1,34,3,2]))

tensor(125)

In [42]:
torch.transpose(f, 0, 1)

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [43]:
torch.det(torch.rand(3,3))

tensor(-0.1372)

In [44]:
torch.rand((3,3)) > torch.rand((3,3))

tensor([[ True,  True, False],
        [ True, False,  True],
        [False, False, False]])

In [45]:
k = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
k

tensor([[3., 8., 9.],
        [3., 7., 8.]])

In [46]:
torch.log(k), torch.exp(k), torch.sqrt(k), torch.sigmoid(k), torch.softmax(k, dim=0), torch.relu(k)

(tensor([[1.0986, 2.0794, 2.1972],
         [1.0986, 1.9459, 2.0794]]),
 tensor([[  20.0855, 2980.9580, 8103.0840],
         [  20.0855, 1096.6332, 2980.9580]]),
 tensor([[1.7321, 2.8284, 3.0000],
         [1.7321, 2.6458, 2.8284]]),
 tensor([[0.9526, 0.9997, 0.9999],
         [0.9526, 0.9991, 0.9997]]),
 tensor([[0.5000, 0.7311, 0.7311],
         [0.5000, 0.2689, 0.2689]]),
 tensor([[3., 8., 9.],
         [3., 7., 8.]]))

In [47]:
## inplace operations
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])
tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])


In [48]:
m +n

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [49]:
# store the result on m + n in the memory of m
m.add_(n)

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [50]:
torch.relu(m)

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [51]:
m.relu_()

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [52]:
# copying a tensor
a = torch.rand(2,3)
a

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [53]:
b = a

In [54]:
b

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [55]:
a[0][0] =0

In [56]:
a

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [57]:
b # even b[0][0] got updated

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [58]:
id(b), id(a) # memory location of b

(133022991818512, 133022991818512)

In [59]:
# to avoid that
b = a.clone()

In [60]:
b

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [61]:
a[0][0]=10

In [62]:
a, b

(tensor([[10.0000,  0.7980,  0.8399],
         [ 0.1374,  0.2331,  0.9578]]),
 tensor([[0.0000, 0.7980, 0.8399],
         [0.1374, 0.2331, 0.9578]]))

In [63]:
id(a), id(b)

(133022991818512, 133022991818704)

In [64]:
device

'cuda'

In [66]:
# tensor operation on GPU
torch.rand((2,3), device=device)


tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [68]:
# moving an exisiting tensor to GPU:
b = a.to(device)

In [69]:
b + 5

tensor([[15.0000,  5.7980,  5.8399],
        [ 5.1374,  5.2331,  5.9578]], device='cuda:0')

In [70]:
import time
size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size,size)

start = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end = time.time()

print("on CPU: ", end-start)

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
end = time.time()
print("on GPU: ", end-start)



on CPU:  28.088135957717896
on GPU:  0.15032434463500977


In [75]:
# reshaping tensors:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [77]:
# flatten: get into single dimension
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [78]:
b = torch.rand(2,3,4)
b

tensor([[[0.2074, 0.0429, 0.1217, 0.9319],
         [0.6632, 0.0663, 0.2821, 0.1318],
         [0.0690, 0.5509, 0.0119, 0.3645]],

        [[0.5644, 0.8473, 0.0240, 0.7587],
         [0.4538, 0.8144, 0.2974, 0.5387],
         [0.8459, 0.9872, 0.5965, 0.5405]]])

In [80]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [82]:
c = torch.rand(226, 226, 3)
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [83]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

In [84]:
## numpy and pytorch
import numpy as np

In [85]:
a = torch.tensor([1,2,3])
b = a.numpy()

In [86]:
type(a), type(b)

(torch.Tensor, numpy.ndarray)

In [87]:
c = np.array([1,24,5])
torch.from_numpy(c)

tensor([ 1, 24,  5])